---
title: "funcomics"
author: "Jan Lanzer"
date: "7/20/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(progeny)
library(dorothea)
library(decoupleR)

data= readRDS("data/data.limma_filt.rds")
```

## SFB - pilot analysis of Artrial Fibrillation patients


```{r volacano}
ttable.corrected= data$limma$limma_cor  %>% mutate(col= ifelse((abs(logFC) > 1.5) & (adj.P.Val< 0.05), "sig", "not.sig"))

ttable.corrected %>% ggplot(., aes(x= logFC, y= -log10(adj.P.Val), col= col))+
  geom_point()+
  theme_minimal()
```

```{r PCA}
## change data type of target
target= data$target[]

data$target= cbind( target[1:grep("MCHC", colnames(target))],
                target[,grep("AFstage", colnames(target)):dim(target)[2]] %>% mutate_all(as.factor)
                )

target= data$target

#run PCA
ExpMat= data$GEX$voom_count

PCA <- prcomp(t(ExpMat) ,center = TRUE, scale. = T)
plot.pca = PCA$x %>%
  as.data.frame %>% 
  rownames_to_column("sample") %>% 
  as_tibble()%>% 
  left_join(data$target %>% rename(sample = sampleID) )

p.pca = ggplot(plot.pca,aes(x= PC1, y= PC2,color = group))+
  geom_point(size= 3)+
  theme_minimal()+ 
  labs(x= paste0("PC1 (",as.character(round(PCA$sdev[1]^2/sum(PCA$sdev^2)*100)),"%)"),
       y= paste("PC2 (",as.character(round(PCA$sdev[2]^2/sum(PCA$sdev^2)*100)),"%)"))+
   geom_text(aes(label=sample,hjust=0,vjust=0))

map_pcas= F
if(map_pcas){
  map(colnames(data$target[2:length(colnames(data$target))]), function(x){
  plot.pc = plot.pca %>% dplyr::rename(vars =  {{x}} ) 
  
  if(is.numeric(plot.pc$vars)){

    plot.pc %>%
    ggplot(.,aes(x= PC1, y= PC2, size = vars))+
    geom_point()+
    theme_minimal()+
    labs(x= paste0("PC1 (",as.character(round(PCA$sdev[1]^2/sum(PCA$sdev^2)*100)),"%)"),
         y= paste("PC2 (",as.character(round(PCA$sdev[2]^2/sum(PCA$sdev^2)*100)),"%)"))+
      ggtitle(paste0("variable: ", x))
  }else if(!is.numeric(plot.pc$vars)){
    plot.pc %>%
    ggplot(.,aes(x= PC1, y= PC2, color = vars))+
    geom_point(size= 3)+
    theme_minimal()+
    labs(x= paste0("PC1 (",as.character(round(PCA$sdev[1]^2/sum(PCA$sdev^2)*100)),"%)"),
         y= paste("PC2 (",as.character(round(PCA$sdev[2]^2/sum(PCA$sdev^2)*100)),"%)"))+
      ggtitle(paste0("variable: ", x))
  }
})
  
}

## Q2 PCA loadings and toptable?
pca.genes= PCA$rotation[,1] %>% as_tibble(rownames = "gene") %>% arrange(desc(value))
plot(pca.genes$value)

library(fgsea)

stats= data$limma$limma_cor %>% pull(t)
names(stats) = data$limma$limma_cor$gene
pathways= list("pc1.genes"= pca.genes$gene[1:100])
fgsea.res= fgseaSimple(stats = stats,pathways = pathways, nperm = 1000)
print(fgsea.res)
plotEnrichment(pathway = pathways$pc1.genes, stats = stats) + labs(title="important genes in pc1")

```


```{r progeny}
library(pheatmap)

ExpMat= data$GEX$voom_count

prog_res= progeny(as.matrix(ExpMat), scale = T, organism = "Human")

Activity_counts <- as.vector(prog_res)

paletteLength <- 100
myColor <-  colorRampPalette(c("darkblue", "whitesmoke","indianred"))(paletteLength)

progenyBreaks <- c(seq(min(Activity_counts), 0, 
                       length.out=ceiling(paletteLength/2) + 1),
                   seq(max(Activity_counts)/paletteLength, 
                       max(Activity_counts), 
                       length.out=floor(paletteLength/2)))

# progeny_hmap <- pheatmap(t(prog_res),fontsize=14, 
#                          fontsize_row = 10, fontsize_col = 10, 
#                          color=myColor, breaks = progenyBreaks, 
#                          main = "PROGENy (100)", angle_col = 45,
#                          treeheight_col = 0,  border_color = NA)
# 
# progeny_hmap

library(ComplexHeatmap)
ha = HeatmapAnnotation(Afib= data$target$group,
    col = list(Afib = c("CT" = "blue", "AF" = "green")))

Heatmap(t(prog_res), top_annotation = ha)

```

```{r dorothea}

## We load Dorothea Regulons
data(dorothea_hs, package = "dorothea")
regulons <- dorothea_hs %>%
  dplyr::filter(confidence %in% c("A", "B","C"))

ttop_Afib_vs_CT <- data$limma$limma_cor %>% 
    dplyr::select(gene, t) %>% 
    dplyr::filter(!is.na(t)) %>% 
    column_to_rownames(var = "gene") %>%
    as.matrix()

tf_activities_stat <- dorothea::run_viper(ttop_Afib_vs_CT, regulons,
    options =  list(minsize = 5, eset.filter = FALSE, 
    cores = 1, verbose = FALSE, nes = TRUE))

tf_activities_stat_top25 <- tf_activities_stat %>%
    as.data.frame() %>% 
    rownames_to_column(var = "GeneID") %>%
    dplyr::rename(NES = "t") %>%
    dplyr::top_n(25, wt = abs(NES)) %>%
    dplyr::arrange(NES) %>% 
    dplyr::mutate(GeneID = factor(GeneID))

ggplot(tf_activities_stat_top25,aes(x = reorder(GeneID, NES), y = NES)) + 
    geom_bar(aes(fill = NES), stat = "identity") +
    scale_fill_gradient2(low = "darkblue", high = "indianred", 
        mid = "whitesmoke", midpoint = 0) + 
    theme_minimal() +
    theme(axis.title = element_text(face = "bold", size = 12),
        axis.text.x = 
            element_text(angle = 45, hjust = 1, size =10, face= "bold"),
        axis.text.y = element_text(size =10, face= "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
    xlab("Transcription Factors")

```

```{r Identification of hclust}

# cluster all: 
cluster.plot= column_to_rownames(plot.pca[1:10], var= "sample")
d= dist(cluster.plot, method = "euclidean")

clust.pca= hclust(d = d, method = "ward.D2")
plot(clust.pca)


cut_the_tree = function(k, plot.pca, clust.obj){
  clust.res= cbind("sampleID"= plot.pca$sample,
      "tree" = cutree(clust.obj, k = k)) %>% as_tibble() %>% 
    left_join(target) %>% 
    left_join(rownames_to_column(cluster.plot, "sampleID"))

print(table(clust.res$group, clust.res$tree))


ggplot(clust.res,aes(x= PC1, y= PC2,color = tree, shape= group))+
  geom_point(size= 3)+
  theme_minimal()+ 
  labs(x= paste0("PC1 (",as.character(round(PCA$sdev[1]^2/sum(PCA$sdev^2)*100)),"%)"),
       y= paste("PC2 (",as.character(round(PCA$sdev[2]^2/sum(PCA$sdev^2)*100)),"%)"), 
       col= "k")
  
  
}

cut_the_tree(2, plot.pca, clust.pca)
cut_the_tree(3, plot.pca, clust.pca)
cut_the_tree(4, plot.pca, clust.pca)
cut_the_tree(5, plot.pca, clust.pca)

```

```{r}
## cluster clinical
## compare loadings with de genes
# 
# t= target %>% select(is.numeric)
# 
# na.omit(cov(t))
# 
# scaled.t = scale(x= t, center = T, scale= T)
# d= dist(scaled.t, method = "euclidean")
# 
# princomp()
# 
# clust.clin= hclust(d = d, method = "ward.D2")
# plot(clust.clin)

cat.data= as.data.frame(target%>% select(is.factor))
rownames(cat.data)= target$sampleID
clust.cat= dist(cat.data,method = "binary")
hclust.cat= hclust(clust.cat, method = "ward.D2")
plot(hclust.cat)

```
